
spring:
  application:
    name: APIGateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth_API
          uri: lb://Auth_API
          predicates:
            - Path=/api/auth/**

        - id: Hotel_API
          uri: lb://Hotel_API
          predicates:
            - Path=/api/hotel/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # ??a ch? Eureka Server
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8083
