server:
  port: 8081

spring:
  application:
    name: Auth_API

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: quyen
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

